### ISSUE TITLE
github call  bytebase api fail issue

### ISSUE THREAD

**Issue by chunlin-huang** [bytebase/github-action-example#27]
Hi,

I deploy the bytebase v2.22.3 on  eks and git action running failed. would you give me some suggestions ? thx
----------git action logs -------------------------------------------------------
Run ./.github/actions/login
Login successful for user: username@****.com. Token obtained.

Run ./.github/actions/sql-review
  with:
    github-token: ***
    pattern: **/*.up.sql
    url: https://database-****.com
    token: ***
    headers: {"Accept-Encoding": "deflate, gzip"}
    database: instances/rdsmysql/databases/demodb
    fail-on-warnings: true
  env:
    BYTEBASE_URL: https://database-****.com
    BYTEBASE_SERVICE_ACCOUNT: username@****.com
    DATABASE: instances/rdsmysql/databases/demodb
Error: Failed to check SQL file demo/test.up.sql with response code 500

--------------error log on the server side as below -------------------------------------------------------

│ "server error" method=/bytebase.v1.SQLService/Check error="rpc error: code = Internal desc = **failed to populate raw resources failed to get database \"instances/rdsmysql/databases/demodb\": instance not found**" latency=2ms

**Comment by tianzhou** [comment]
Does `rdsmysql` match the instance-id here?

![CleanShot 2024-09-13 at 11 33 59](https://github.com/user-attachments/assets/ce47a4eb-e951-4481-b144-cf86e06b738f)

**Comment by chunlin-huang** [comment]
I change the instance name: rdsmysql to instance ID, it work now.
Thanks for your guide
